require("prototypes.public")
require("prototypes.container-gen")
require("prototypes.inventory-sizes")
require("prototypes.container-subgroups")
require("compatibility.IndustrialRevolution3.data-final-fixes")
