require("prototypes.public")
require("prototypes.technology")
require("compatibility.bobs.data-updates")
require("compatibility.krastorio2.data-updates")
require("compatibility.AdvancedBelts.data-updates")
require("compatibility.IndustrialRevolution3.data-updates")
